### ISSUE TITLE
Updated Docs

### ISSUE THREAD

**Issue by mastastealth** [livingstyleguide/broccoli-livingstyleguide#2]
Trying to get this working on Ember CLI, with Ember 1.13.1 but I'm having trouble with the documentation:

- "Add to the plugin to your dependencies in your package.json:", there is a "devDependencies" in my JSON, not a simple "dependencies". I imagine this is where I would add the line now?

- " Assuming you have a stylesheet called app/styles/app.scss (as Ember CLI does) add this your Brocfile.js", I don't have a Brocfile.js, I assume this is ember-cli-build.js now?

- I don't know where to add those 3 lines for the JS, when my default looks like:
```
/* global require, module */
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    // options
  });

  return app.toTree();
};
```
I imagine the follow 2 can just go under the first line:
```
var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var LivingStyleGuide = require('broccoli-livingstyleguide');
var lsg = LivingStyleGuide(['app'], 'styles/styleguide.lsg', 'assets/styleguide.html');
```
but then where do I stick in ``module.exports = mergeTrees([app.toTree(), lsg]);`` ?

**Comment by hagenburger** [comment]
Hey Brian, I need to find out myself as I haven’t been working with the latest Ember versions yet. I’m organizing a conference on the weekend so it might be difficult to find an answer for you in time. Let me know, if you found out anything yourself first.

**Comment by mydea** [comment]
I got it to work by manually installing broccoli-merge-trees via npm, and then doing something like this in ember-cli-build.js:

```
var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var mergeTrees = require('broccoli-merge-trees');
var LivingStyleGuide = require('broccoli-livingstyleguide');

var lsg = LivingStyleGuide(['app'], 'styles/styleguide.lsg', 'assets/styleguide.html');

module.exports = function (defaults) {
    var app = new EmberApp(defaults, {
        // Add options here
    });

    return mergeTrees([app.toTree(), lsg]);
};
```

**Comment by hagenburger** [comment]
@mastastealth I hope this solves it for you. Reopen if not.

@mydea thank you! I think we should add your code to the [README](https://github.com/livingstyleguide/broccoli-livingstyleguide/blob/master/README.md). What do you think?
